set -x
# python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/fno_attack_config.toml
# python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/fno_attack_downsample_config.toml
# python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/fno_attack_upsample_config.toml
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_consistency.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_consistency
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_pgd_spatial_stealth.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_pgd_spatial_stealth
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_pgd_spatial_stealth.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_pgd_spectral_stealth
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_pgd_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_pgd_spectral
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_mvmo.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_mvmo
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_boundary.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_boundary
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_noise_spectral.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_noise_spectral
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/fno/clean/attack_noise_spatial.h5 --output_dir=simple/darcy_2d/eval/fno/attack/clean/attack_noise_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/attack/fno/downsample/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/fno/attack/downsample/attack_pgd_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/attack/fno/downsample/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/fno/attack/downsample/attack_pgd_spectral
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/attack/fno/upsample/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/fno/attack/upsample/attack_pgd_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/attack/fno/upsample/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/fno/attack/upsample/attack_pgd_spectral

# python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/ffno_attack_config.toml
# python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/ffno_attack_downsample_config.toml
#python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/ffno_attack_upsample_config.toml
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_consistency.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_consistency
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_pgd_spatial_stealth.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_pgd_spatial_stealth
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_pgd_spatial_stealth.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_pgd_spectral_stealth
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_pgd_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_pgd_spectral
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_mvmo.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_mvmo
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_boundary.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_boundary
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_noise_spectral.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_noise_spectral
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/ffno/clean/attack_noise_spatial.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/clean/attack_noise_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/attack/ffno/downsample/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/downsample/attack_pgd_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/attack/ffno/downsample/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/downsample/attack_pgd_spectral
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/attack/ffno/upsample/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/upsample/attack_pgd_spatial
# python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/attack/ffno/upsample/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/ffno/attack/upsample/attack_pgd_spectral


#python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/cno_attack_config.toml
#python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/cno_attack_downsample_config.toml
#python -m simple.darcy_2d.attack --attack_config=simple/darcy_2d/cno_attack_upsample_config.toml
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_consistency.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_consistency
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_pgd_spatial_stealth.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_pgd_spatial_stealth
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_pgd_spatial_stealth.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_pgd_spectral_stealth
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_pgd_spatial
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_pgd_spectral
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_mvmo.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_mvmo
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_boundary.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_boundary
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_noise_spectral.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_noise_spectral
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/attack/cno/clean/attack_noise_spatial.h5 --output_dir=simple/darcy_2d/eval/cno/attack/clean/attack_noise_spatial
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/attack/cno/downsample/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/cno/attack/downsample/attack_pgd_spatial
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/attack/cno/downsample/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/cno/attack/downsample/attack_pgd_spectral
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/attack/cno/upsample/attack_pgd_spatial.h5 --output_dir=simple/darcy_2d/eval/cno/attack/upsample/attack_pgd_spatial
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/attack/cno/upsample/attack_pgd_spectral.h5 --output_dir=simple/darcy_2d/eval/cno/attack/upsample/attack_pgd_spectral

set +x