set -x
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean.h5 --output_dir=simple/darcy_2d/eval/fno/clean/clean
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean.h5 --output_dir=simple/darcy_2d/eval/ffno/clean/clean
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_128.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean.h5 --output_dir=simple/darcy_2d/eval/cno/clean/clean
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean_256.h5 --output_dir=simple/darcy_2d/eval/fno/clean/upsample
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean_256.h5 --output_dir=simple/darcy_2d/eval/ffno/clean/upsample
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_256.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean_256.h5 --output_dir=simple/darcy_2d/eval/cno/clean/upsample
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/fno_model.toml --model_path=simple/darcy_2d/trained_models/best_fno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean_64.h5 --output_dir=simple/darcy_2d/eval/fno/clean/downsample
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/ffno_model.toml --model_path=simple/darcy_2d/trained_models/best_ffno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean_64.h5 --output_dir=simple/darcy_2d/eval/ffno/clean/downsample
python -m simple.darcy_2d.evaluate --model_config=simple/darcy_2d/cno_model.toml --model_path=simple/darcy_2d/trained_models/best_cno_model.pth --data_config=simple/darcy_2d/data_64.toml --data_path=simple/darcy_2d/data/pdebench_darcy_clean_64.h5 --output_dir=simple/darcy_2d/eval/cno/clean/downsample
set +x