set -x

python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spatial --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spatial_stealth --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spatial_stealth.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spectral --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spectral_stealth --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spectral_stealth.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_noise_spatial --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_noise_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_noise_spectral --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_noise_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_sequential_spatial --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_sequential_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_sequential_spectral --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_sequential_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spatial_downsample --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spatial.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_32.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spectral_downsample --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spectral.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_32.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spatial_upsample --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spatial.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_128.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno/attack_001/attack_pgd_spectral_upsample --data_path=temporal/ns_2d/data/attack/cno/eps001/attack_pgd_spectral.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_128.h5


python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spatial --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spatial_stealth --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spatial_stealth.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spectral --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spectral_stealth --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spectral_stealth.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_noise_spatial --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_noise_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_noise_spectral --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_noise_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_sequential_spatial --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_sequential_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_sequential_spectral --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_sequential_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spatial_downsample --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spatial.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_32.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spectral_downsample --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spectral.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_32.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spatial_upsample --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spatial.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_128.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno/attack_001/attack_pgd_spectral_upsample --data_path=temporal/ns_2d/data/attack/ffno/eps001/attack_pgd_spectral.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_128.h5


python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/clean/clean --data_path=temporal/ns_2d/data/data_100_50steps/ns_data_64.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spatial --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spatial_stealth --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spatial_stealth.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spectral --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spectral_stealth --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spectral_stealth.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_noise_spatial --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_noise_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_noise_spectral --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_noise_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_sequential_spatial --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_sequential_spatial.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_sequential_spectral --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_sequential_spectral.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spatial_downsample --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spatial.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_32.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spectral_downsample --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spectral.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_32.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spatial_upsample --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spatial.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_128.h5
python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001/attack_pgd_spectral_upsample --data_path=temporal/ns_2d/data/attack/fno/eps001/attack_pgd_spectral.h5 --ref_data_path temporal/ns_2d/data/data_100_50steps/ns_data_128.h5

# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_pgd_spatial --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_pgd_spatial.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_pgd_spatial_stealth --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_pgd_spatial_stealth.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_pgd_spectral --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_pgd_spectral.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_pgd_spectral_stealth --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_pgd_spectral_stealth.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_noise_spatial --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_noise_spatial.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_noise_spectral --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_noise_spectral.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_001_without_physics/attack_sequential --data_path=temporal/ns_2d/data/attack/fno/eps001_without_physics/attack_sequential.h5


# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/clean/clean --data_path=temporal/ns_2d/data/data_100_50steps_s64/ns_data.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_pgd_spatial --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_pgd_spatial.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_pgd_spatial_stealth --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_pgd_spatial_stealth.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_pgd_spectral --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_pgd_spectral.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_pgd_spectral_stealth --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_pgd_spectral_stealth.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_noise_spatial --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_noise_spatial.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_noise_spectral --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_noise_spectral.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_mvmo --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_mvmo.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_boundary --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_boundary.h5
# python -m temporal.ns_2d.evaluate --model_config=temporal/ns_2d/fno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_fno_model.pth --output_dir=temporal/ns_2d/eval/fno/attack_without_physics/attack_consistency --data_path=temporal/ns_2d/data/attack/fno/without_physics/attack_consistency.h5

#python -m temporal.ns_2d.evaluate_attack --model_config=temporal/ns_2d/ffno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_ffno_model.pth --output_dir=temporal/ns_2d/eval/ffno
#python -m temporal.ns_2d.evaluate_attack --model_config=temporal/ns_2d/cno_model.toml --data_config=temporal/ns_2d/attack_data.toml --model_path=temporal/ns_2d/trained_models/best_cno_model.pth --output_dir=temporal/ns_2d/eval/cno

set +x
